replicaCount: 2

image:
  repository: vivekbangare01/python-app-5
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "python-app-5-dev-latest"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
